#ifndef SCREENLAYOUT_GLOBAL_H
#define SCREENLAYOUT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SCREENLAYOUT_LIBRARY)
#  define SCREENLAYOUTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCREENLAYOUTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCREENLAYOUT_GLOBAL_H
